name: CI Pipeline Demo
on: #trigger on push command
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🧪 Run Tests
        run: npm test

      - name: ✅ Success Message
        if: success()
        run: echo "All tests passed successfully!"

      - name: ❌ Failure Message
        if: failure()
        run: echo "Tests failed! Please fix errors."
